version: '3.4'

services:
   
  # mlproduction:
  #   image: mlproduction
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - 5000:5000
  #   environment:
  #     - FLASK_APP=/app/src/server.py
  #     - FLASK_DEBUG=true
  #     - MLP_TFS_URL=http://tfs:8501
  #     - MLP_PIPE_PATH=/app/pipeline.joblib
  #   depends_on: 
  #     - tfs
  #   volumes:
  #     - ./src/tests/test_pipe.joblib:/app/pipeline.joblib
  #   command:
  #     - pipenv
  #     - run
  #     - flask
  #     - run
  #     - -h
  #     - '0.0.0.0'

  tfs:
    build: 
      context: .
      dockerfile: ./Dockerfile.serving
    ports:
      - 8501:8501 
