apiVersion: skaffold/v2beta9
kind: Config
build:
  artifacts:
  - image: tf-model
    context: .
    docker:
      dockerfile: Dockerfile.serving
deploy:
  kubectl:
    defaultNamespace: prod
    manifests:
      - kubernetes/**
