apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-production-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ml-production
  template:
    metadata:
      labels:
        app: ml-production
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8501'
        prometheus.io/path: '/monitoring/prometheus/zmetrics'
    spec:
      volumes:
        - name: ml-config 
          configMap:
            name: ml-production-deployment
      imagePullSecrets:
        - name: gcr-json-key
      containers:
      - name: tf-model
        image: tf-model
        volumeMounts:
          - mountPath: /etc/ml
            name: ml-config
        args:
          - --monitoring_config_file=/etc/ml/prometheus.config
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "2Gi"
            cpu: "1"
        ports:
          - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: ml-production-service
spec:
  type: NodePort
  selector:
    app: ml-production 
  ports:
  - port: 8501
    targetPort: 8501
