apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-production-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ml-production
  template:
    metadata:
      labels:
        app: ml-production
    spec:
      imagePullSecrets:
        - name: gcr-json-key
      containers:
      - name: ml-production
        image: ml-production
        env:
          - name: MLP_TFS_URL
            value: http://localhost:8501
          - name: MLP_PIPE_PATH
            value: /pipeline/pipe.joblib
          - name: FLASK_APP
            value: /app/src/server.py
          - name: FLASK_DEBUG
            value: "true"
          - name: PYTHONUNBUFFERED
            value: "1"
        command:
          - pipenv
          - run
          - flask
          - run
          - -h
          - 0.0.0.0
        resources:
          requests:
            memory: "320Mi"
            cpu: "100m"
          limits:
            memory: "2Gi"
            cpu: "1"
        ports:
        - containerPort: 5000
      - name: tf-model
        image: tf-model
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "2Gi"
            cpu: "1"
        ports:
          - containerPort: 8501

---
apiVersion: v1
kind: Service
metadata:
  name: ml-production-service
spec:
  type: NodePort
  selector:
    app: ml-production 
  ports:
  - port: 5000
    targetPort: 5000
